### PR TITLE
add bits and rate functions

### PR DESCRIPTION
**Pull request by Zergity**
`bits()` count the bits set in the filter
`rate()` estimate false-positive rate

### CODE REVIEW

**Comment by jasondavies** [comment]
Done in 90d0d6e159e2ca71f0ed355bc0b2162ea2ced556.

**Comment by Zergity** [comment]
A friendly question: Why don't you (rebase and) merge the PR?

FYI: committing the same change without merging is considered stealing contribution.

**Comment by jasondavies** [comment]
Accusing me of stealing a contribution because I implemented it myself is not a friendly question.

**Comment by Zergity** [comment]
It's simply open source and programmer ethics to acknowledge the contributions of others.

I hope you will understand it someday.

**Comment by jasondavies** [comment]
I'm sorry that you feel like you weren't properly credited.  We are talking about a single line of code that estimates the false positive rate, which can only really be implemented sensibly in one way.

Of course, it would have been more inclusive of your contribution if I had modified your PR or mentioned your handle in my commit.  Maybe one way to resolve this would be if you made a PR including your test case for the new error function?

**Comment by Zergity** [comment]
Nevermind that, just a friendly reminder.

Godspeed, fellow!

**Pull request closed without merging**
